/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as CertificacoesRouteImport } from './routes/certificacoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as EspecializacoesRouteImport } from './routes/especializacoes'
import { Route as PlanoAcaoRouteImport } from './routes/plano-acao'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as RevendasIndexRouteImport } from './routes/revendas.index'
import { Route as RevendasIdRouteImport } from './routes/revendas.$id'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsAreaRouteImport } from './routes/solutions.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificacoesRoute = CertificacoesRouteImport.update({
  id: '/certificacoes',
  path: '/certificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecializacoesRoute = EspecializacoesRouteImport.update({
  id: '/especializacoes',
  path: '/especializacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoAcaoRoute = PlanoAcaoRouteImport.update({
  id: '/plano-acao',
  path: '/plano-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendasIndexRoute = RevendasIndexRouteImport.update({
  id: '/revendas/',
  path: '/revendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendasIdRoute = RevendasIdRouteImport.update({
  id: '/revendas/$id',
  path: '/revendas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAreaRoute = SolutionsAreaRouteImport.update({
  id: '/solutions/$area',
  path: '/solutions/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/certificacoes': typeof CertificacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copilot': typeof CopilotRoute
  '/especializacoes': typeof EspecializacoesRoute
  '/plano-acao': typeof PlanoAcaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/chat': typeof ApiChatRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/revendas/$id': typeof RevendasIdRoute
  '/solutions/$area': typeof SolutionsAreaRoute
  '/clientes/': typeof ClientesIndexRoute
  '/revendas/': typeof RevendasIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/certificacoes': typeof CertificacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copilot': typeof CopilotRoute
  '/especializacoes': typeof EspecializacoesRoute
  '/plano-acao': typeof PlanoAcaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/chat': typeof ApiChatRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/revendas/$id': typeof RevendasIdRoute
  '/solutions/$area': typeof SolutionsAreaRoute
  '/clientes': typeof ClientesIndexRoute
  '/revendas': typeof RevendasIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/certificacoes': typeof CertificacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copilot': typeof CopilotRoute
  '/especializacoes': typeof EspecializacoesRoute
  '/plano-acao': typeof PlanoAcaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/chat': typeof ApiChatRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/revendas/$id': typeof RevendasIdRoute
  '/solutions/$area': typeof SolutionsAreaRoute
  '/clientes/': typeof ClientesIndexRoute
  '/revendas/': typeof RevendasIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficios'
    | '/certificacoes'
    | '/configuracoes'
    | '/copilot'
    | '/especializacoes'
    | '/plano-acao'
    | '/relatorios'
    | '/api/chat'
    | '/clientes/$id'
    | '/revendas/$id'
    | '/solutions/$area'
    | '/clientes/'
    | '/revendas/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficios'
    | '/certificacoes'
    | '/configuracoes'
    | '/copilot'
    | '/especializacoes'
    | '/plano-acao'
    | '/relatorios'
    | '/api/chat'
    | '/clientes/$id'
    | '/revendas/$id'
    | '/solutions/$area'
    | '/clientes'
    | '/revendas'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/beneficios'
    | '/certificacoes'
    | '/configuracoes'
    | '/copilot'
    | '/especializacoes'
    | '/plano-acao'
    | '/relatorios'
    | '/api/chat'
    | '/clientes/$id'
    | '/revendas/$id'
    | '/solutions/$area'
    | '/clientes/'
    | '/revendas/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeneficiosRoute: typeof BeneficiosRoute
  CertificacoesRoute: typeof CertificacoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CopilotRoute: typeof CopilotRoute
  EspecializacoesRoute: typeof EspecializacoesRoute
  PlanoAcaoRoute: typeof PlanoAcaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ApiChatRoute: typeof ApiChatRoute
  ClientesIdRoute: typeof ClientesIdRoute
  RevendasIdRoute: typeof RevendasIdRoute
  SolutionsAreaRoute: typeof SolutionsAreaRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  RevendasIndexRoute: typeof RevendasIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificacoes': {
      id: '/certificacoes'
      path: '/certificacoes'
      fullPath: '/certificacoes'
      preLoaderRoute: typeof CertificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especializacoes': {
      id: '/especializacoes'
      path: '/especializacoes'
      fullPath: '/especializacoes'
      preLoaderRoute: typeof EspecializacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-acao': {
      id: '/plano-acao'
      path: '/plano-acao'
      fullPath: '/plano-acao'
      preLoaderRoute: typeof PlanoAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendas/': {
      id: '/revendas/'
      path: '/revendas'
      fullPath: '/revendas/'
      preLoaderRoute: typeof RevendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendas/$id': {
      id: '/revendas/$id'
      path: '/revendas/$id'
      fullPath: '/revendas/$id'
      preLoaderRoute: typeof RevendasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$area': {
      id: '/solutions/$area'
      path: '/solutions/$area'
      fullPath: '/solutions/$area'
      preLoaderRoute: typeof SolutionsAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeneficiosRoute: BeneficiosRoute,
  CertificacoesRoute: CertificacoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CopilotRoute: CopilotRoute,
  EspecializacoesRoute: EspecializacoesRoute,
  PlanoAcaoRoute: PlanoAcaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  ApiChatRoute: ApiChatRoute,
  ClientesIdRoute: ClientesIdRoute,
  RevendasIdRoute: RevendasIdRoute,
  SolutionsAreaRoute: SolutionsAreaRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  RevendasIndexRoute: RevendasIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
